### PR TITLE
Add error handling for ParseGppSubSections

### PR DESCRIPTION
**Pull request by shkumar-viantinc**
We are seeing panics coming from accessing NULL object returned from ParseGppSubSections

### CODE REVIEW

**Comment by shkumar-viantinc** [comment]
@kylehalverson Please review this thanks

**Comment by kylehalverson** [comment]
> @kylehalverson Please review this thanks

@shkumar-viantinc Do you have an example Consent String that displays the behavior you are seeing? Thanks!

**Comment by shkumar-viantinc** [comment]
@kylehalverson we haven't logged the string in our codebase but I think this change is helpful since ParseGppSubSections does return nil values in some cases.

**Comment by shkumar-viantinc** [comment]
@kylehalverson Following up on this. Let me know, thanks

**Comment by kylehalverson** [comment]
> @kylehalverson Following up on this. Let me know, thanks

Thanks @shkumar-viantinc, I am trying to understand the problem without the test string showing the behavior. I think that the issue you are saying is that normally GPC subsection can be true/false/nil. You're seeing instances where the GPC is nil, but you're saying it is because of a bad subsection, and you want to distinguish that? If that is the case, would it work if we return the consent up until that point along with the error, i.e.
```
		if err != nil {
			return p, err
		}
```
Please let me know if I am misunderstanding.

**Comment by shkumar-viantinc** [comment]
> > @kylehalverson Following up on this. Let me know, thanks
> 
> Thanks @shkumar-viantinc, I am trying to understand the problem without the test string showing the behavior. I think that the issue you are saying is that normally GPC subsection can be true/false/nil. You're seeing instances where the GPC is nil, but you're saying it is because of a bad subsection, and you want to distinguish that? If that is the case, would it work if we return the consent up until that point along with the error, i.e.
> 
> ```
> 		if err != nil {
> 			return p, err
> 		}
> ```
> 
> Please let me know if I am misunderstanding.

@kylehalverson What you said makes sense, I think we can return the  consent up until that point along with the error. I will update the PR

**Comment by kylehalverson** [comment]
I opened [this PR](https://github.com/LiveRamp/iabconsent/pull/34) to also update the new MSPAs that were recently added, and to add in tests to display the error and expected behavior more explicitly. Will close this PR for now in favor of that one.

**Pull request closed without merging**
