### PR TITLE
Replace panics with errors

### PR DESCRIPTION
**Pull request by rupertchen**
This change addresses the concerns raised in LiveRamp/iabconsent#5. It
replaces the use of panics with returned errors and introduces breaking
changes to ConsentReader. The returned errors now include stack traces
which can be seen with the "%+v" format verb.

Parse() remains backwards compatible.

---
This change is [Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/7)

### CODE REVIEW

**Review by adayNU — CHANGES_REQUESTED** [review]
Had one concern around the returned error being misleading, but otherwise looks good.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/7#-:-LLfTi5E6Qbbl2z6QVq6:b-bt26at)* status: all files reviewed, 2 unresolved discussions (waiting on @rupertchen)

___
*[parse.go, line 111 at r1](https://reviewable.io/reviews/liveramp/iabconsent/7#-LLfSBB6ET2OaDX_TBzJ:-LLfSBB6ET2OaDX_TBzK:bb8s472) ([raw file](https://github.com/liveramp/iabconsent/blob/5bd07aa4fd58317ccf6be604352abaa4a6c57fbe/parse.go#L111)):*
> ```Go
> 	var b, err = base64.RawURLEncoding.DecodeString(s)
> 	if err != nil {
> 		return nil, err
> ```

Should we also `Wrap` / `WithMessage` this error since it comes from an external package?
___
*[parse.go, line 138 at r1](https://reviewable.io/reviews/liveramp/iabconsent/7#-LLfTGpq5UYPYeTePAkV:-LLfTGpq5UYPYeTePAkW:br70eps) ([raw file](https://github.com/liveramp/iabconsent/blob/5bd07aa4fd58317ccf6be604352abaa4a6c57fbe/parse.go#L138)):*
> ```Go
> 	}
> 
> 	return p, r.Err
> ```

In this case, it appears we would only show the _latest_ error we encountered while reading these bits, correct? If so, could this be misleading to the caller?

**Review by rupertchen — COMMENTED** [review]
@adaynu, PTAL.

> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/7#-:-LMgqx8x8emu3rY6LnuA:b-uwesy)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @adayNU)

___
*[parse.go, line 111 at r1](https://reviewable.io/reviews/liveramp/iabconsent/7#-LLfSBB6ET2OaDX_TBzJ:-LMgkAGv4Jh8RN3De2Ks:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/5bd07aa4fd58317ccf6be604352abaa4a6c57fbe/parse.go#L111)):*
<details><summary><i>Previously, adayNU (Andy Day) wrote…</i></summary><blockquote>

Should we also `Wrap` / `WithMessage` this error since it comes from an external package?
</blockquote></details>

Done.
___
*[parse.go, line 138 at r1](https://reviewable.io/reviews/liveramp/iabconsent/7#-LLfTGpq5UYPYeTePAkV:-LMgkaR809Ga4bCIbhW3:b-i2tv4z) ([raw file](https://github.com/liveramp/iabconsent/blob/5bd07aa4fd58317ccf6be604352abaa4a6c57fbe/parse.go#L138)):*
<details><summary><i>Previously, adayNU (Andy Day) wrote…</i></summary><blockquote>

In this case, it appears we would only show the _latest_ error we encountered while reading these bits, correct? If so, could this be misleading to the caller?
</blockquote></details>

[`bits.Reader`](https://godoc.org/github.com/rupertchen/go-bits#Reader) is designed so that once any read fails, all further `Read*` calls are no-ops that return the same error. This pattern allows the caller to call multiple reads in succession (for code clarity) without having to handle the error response immediately and repeatedly. I got this idea from [Errors are values](https://blog.golang.org/errors-are-values).

Unfortunately, the full code of the example doesn't get rendered in the docs, but there's commentary in its source: https://github.com/rupertchen/go-bits/blob/v0.2.0/example_parse_payload_test.go#L64-L68.

**Review by adayNU — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/7#-:-LNuxb3h7tUcjmJrKj4J:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by adayNU** [comment]
Can we close here @rupertchen ?

**Pull request merged**
